import { Writer } from '../base/writer.js';
import chalk from 'chalk';
import { C64FileInfo } from '../types/index.js';
import { WriterOptions } from '../base/writer.js';
import { CbmFileTypeToValue } from '../readers/t64.js';

export class T64Writer extends Writer {
    constructor(filePath: string, options: WriterOptions = {}) {
        super(filePath, options);
    }

    supportsMultipleFiles(): boolean {
        return true;
    }

    async writeContent(
        files: C64FileInfo[],
        options: WriterOptions = {}
    ): Promise<void> {
        const numFiles = files.length;
        const headerBuffer = Buffer.alloc(64 + numFiles * 32, 0);
        headerBuffer.write('C64S tape image file', 0, 'ascii');
        headerBuffer.writeUInt16LE(0x0100, 32);
        headerBuffer.writeUInt16LE(numFiles, 34);
        headerBuffer.writeUInt16LE(numFiles, 36);
        headerBuffer.fill(' ', 40, 64);
        headerBuffer.write('T64 GENERATED BY C64UTIL 0.1', 40, 'ascii');
        var dataOffset = 64 + numFiles * 32;
        for (var i = 0; i < numFiles; i++) {
            const baseOffset = 64 + i * 32;
            const type =
                CbmFileTypeToValue(files[i].type) || CbmFileTypeToValue('PRG');
            headerBuffer.writeUInt8(1, baseOffset + 0);
            headerBuffer.writeUInt8(type, baseOffset + 1);
            headerBuffer.writeUInt16LE(files[i].startAddr, baseOffset + 2);
            headerBuffer.writeUInt16LE(files[i].endAddr, baseOffset + 4);
            headerBuffer.writeUInt32LE(dataOffset, baseOffset + 8);
            headerBuffer.fill(' ', baseOffset + 16, 16);
            headerBuffer.write(
                files[i].name.padEnd(16, ' '),
                baseOffset + 16,
                'ascii'
            );
            dataOffset += files[i].data.length;
        }
        this.createProgressBar(
            numFiles,
            `  ${chalk.cyan('File :current/:total')} [:bar] :percent | :message`
        );

        this.write(headerBuffer);
        for (let file of files) {
            this.write(file.data);
            this.updateProgress(1, { message: `Writing ${file.name}` });
        }

        this.finishProgress();
    }
}
